apiVersion: v1
kind: Pod
metadata:
  name: springpod
spec:
   containers:
   - name : springappcontainer
     image: barathkawin/spring-boot-application:1
     ports:
     - containerPort: 8080  
   
